$(OBJ_DIR)/cdtd.o: src/xml_src/cdtd.cpp	src/xml_src/cdtd.h
	$(compile_source)

$(OBJ_DIR)/cpars.o: src/xml_src/cpars.cpp	src/xml_src/cpars.h
	$(compile_source)

$(OBJ_DIR)/cerr.o: src/xml_src/cerr.cpp	src/xml_src/cerr.h
	$(compile_source)

$(OBJ_DIR)/chartab.o: src/xml_src/chartab.cpp	src/xml_src/chartab.h
	$(compile_source)

$(OBJ_DIR)/cprop.o: src/xml_src/cprop.cpp	src/xml_src/cprop.h
	$(compile_source)

$(OBJ_DIR)/cstak.o: src/xml_src/cstak.cpp	src/xml_src/cstak.h
	$(compile_source)

$(OBJ_DIR)/cstrm.o: src/xml_src/cstrm.cpp	src/xml_src/cstrm.h
	$(compile_source)

$(OBJ_DIR)/ctag.o: src/xml_src/ctag.cpp	src/xml_src/ctag.h
	$(compile_source)

$(OBJ_DIR)/custr.o: src/xml_src/custr.cpp	src/xml_src/custr.h
	$(compile_source)

$(OBJ_DIR)/cpitem.o: src/cpitem.cpp	src/cpitem.h
	$(compile_source)

$(OBJ_DIR)/ccg.o: src/ccg.cpp
	$(compile_source)

$(OBJ_DIR)/cpatrn.o: src/cpatrn.cpp	src/cpatrn.h
	$(compile_source)

$(OBJ_DIR)/cproc.o: src/cproc.cpp	src/cproc.h
	$(compile_source)

$(OBJ_DIR)/cproccol.o: src/cproccol.cpp src/cproccol.h
	$(compile_source)

$(OBJ_DIR)/copts.o: src/copts.cpp	src/copts.h
	$(compile_source)

$(OBJ_DIR)/cdp.o: src/cdp.cpp	src/cdp.h
	$(compile_source)

$(OBJ_DIR)/cdep.o: src/cdep.cpp	src/cdep.h
	$(compile_source)

$(OBJ_DIR)/cscol.o: src/cscol.cpp	src/cscol.h
	$(compile_source)

$(OBJ_DIR)/ctab.o: src/ctab.cpp	src/ctab.h
	$(compile_source)

$(OBJ_DIR)/ctabcol.o: src/ctabcol.cpp	src/ctabcol.h
	$(compile_source)

$(OBJ_DIR)/cdb.o: src/cdb.cpp	src/cdb.h
	$(compile_source)

$(OBJ_DIR)/cserver.o: src/cserver.cpp	src/cserver.h
	$(compile_source)

$(OBJ_DIR)/parse.o: src/parse.cpp	src/parse.h
	$(compile_source)

$(OBJ_DIR)/prettyprint.o: src/prettyprint.cpp	src/prettyprint.h
	$(compile_source)

$(OBJ_DIR)/nextlevel.o: src/nextlevel.cpp
	$(compile_source)
