
--
-- The PRODUCT_TRIG_I insert trigger is fired when new records in the PRODUCT table are inserted
-- Each new PRODUCT entry causes an insert on PRODUCT_PRICE
--
create trigger PRODUCT_TRIG_I on PRODUCT for INSERT as
begin
INSERT INTO PRODUCT_PRICE
(
   Product_ID,NAMEvc,DESCRIPTIONvc,bVALID
  ,STDRD_PRICE_ID,STDRD_VALID_FROMdt,STDRD_VALID_TOdt,STDRD_PRICEnc,STDRD_CURRENCY_ID
  ,SALES_PRICE_ID,SALES_VALID_FROMdt,SALES_VALID_TOdt,SALES_PRICEnc,SALES_CURRENCY_ID,SALES_DESCRIPTIONvc,SALES_NAMEvc
  ,CAT_NAMEvc,CAT_SUB_NAMEvc,CAT_DESCRIPTIONvc
)
SELECT
   Product_ID    = i.PRODUCT_ID
  ,NAMEvc        = i.NAMEvc
  ,DESCRIPTIONvc = i.DESCRIPTIONvc
  ,bVALID        = i.bVALID
  -- STDRD Records
  ,STDRD_PRICE_ID     = STD_PR.PRICE_ID
  ,STDRD_VALID_FROMdt = STD_PR.VALID_FROMdt
  ,STDRD_VALID_TOdt   = STD_PR.VALID_TOdt
  ,STDRD_PRICEnc      = STD_PR.PRICEnc
  ,STDRD_CURRENCY_ID  = STD_PR.CURRENCY_ID
  -- SALES Records
  ,SALES_PRICE_ID      = SLPR.PRICE_ID
  ,SALES_VALID_FROMdt  = SLPR.VALID_FROMdt
  ,SALES_VALID_TOdt    = SLPR.VALID_TOdt
  ,SALES_PRICEnc       = SLPR.PRICEnc
  ,SALES_CURRENCY_ID   = SLPR.CURRENCY_ID
  ,SALES_DESCRIPTIONvc = SLPR.DESCRIPTIONvc
  ,SALES_NAMEvc        = SLPR.NAMEvc
  --CATEGORY_1_ID    int         not null,
  --CATEGORY_2_ID    int         not null
  ,CAT_NAMEvc          = CAT.NAMEvc
  ,CAT_SUB_NAMEvc      = CAT.SUB_NAMEvc
  ,CAT_DESCRIPTIONvc   = CAT.SUB_NAMEvc
  FROM inserted i, STANDARDPRICE STD_PR, SALESPRICE SLPR, CATEGORY CAT
 WHERE STD_PR.PRICE_ID = i.STDRD_PRICE_ID
   AND SLPR.PRICE_ID   = i.SALES_PRICE_ID
   AND CAT.CAT_1_ID    = i.CATEGORY_1_ID
   AND CAT.CAT_1_ID    = i.CATEGORY_2_ID

end -- End of Trigger
